### ISSUE TITLE
Add link to Discourse forum

### ISSUE THREAD

**Issue by agustinfz** [BanklessHQ/bankless-dao-website#25]
we want to provide a link to the Discourse Forum so that help DAO users can discover the forum, seem what projects are being discussed and get involved

**Comment by wpmonty** [comment]
Scope:
Refactor the Governance navigation item to be a dropdown with two items.
- Forum (https://forum.bankless.community/)
- Vote (https://snapshot.org/#/banklessvault.eth)

This may involve some rework of the existing dropdown implementation, but should be a small lift and good first ticket.

**Comment by Oktalize** [comment]
@wpmonty I will take this one, i'll get working on it right now
