### ISSUE TITLE
Enable 'signup with wallet address' across website

### ISSUE THREAD

**Issue by johokorie** [BanklessHQ/bankless-dao-website#72]
**Describe the solution you'd like**
Add a feature to enable new users to create account on the website with their wallet address across the website and also automatically add Bank token to their wallet. 
Example can be seen at [https://github.com/scaffold-eth/scaffold-eth/tree/sign-in-with-web3/packages/hardhat]

**Comment by wpmonty** [comment]
Thanks for the comment! The current website repo is https://github.com/BanklessDAO/bankless-dao-ghost-website, please reproduce over there. I'll archive this repo as it is no longer active.
